# Generated by Django 5.0.7 on 2024-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0004_userprofile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidcardlog",
            name="rfid_card",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
