# Generated by Django 5.0.7 on 2024-11-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketing", "0005_alter_rfidcardlog_rfid_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfidcardlog",
            name="end_latitude",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="rfidcardlog",
            name="end_longitude",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="rfidcardlog",
            name="rfid_card",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketing.rfidcard",
            ),
        ),
        migrations.AlterField(
            model_name="rfidcardlog",
            name="start_latitude",
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name="rfidcardlog",
            name="start_longitude",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
